### ISSUE TITLE
Implement missing json parser test in lua

### ISSUE THREAD

**Issue by malirod** [malirod/pylua#1]
In `pylua/test/test_json.py` there are not implemented tests.
This should be same tests as in python but in lua

**Comment by AGaliuzov** [comment]
@malirod This is not clear what you mean about the same tests?
AFAIK the lua can't process the json itself

Do you expect the python object parsing within lua? somehow like

``` lua
lua_runtime.eval(python_object_dict[0]) -> int
```

**Comment by malirod** [comment]
@AGaliuzov, yes the idea is to implement some kind of classes\functions which will implement missing functionality in python.
If it's possible, it's better to create some kind of wrapper in lua to encapsulate python calls.

At the moment ATF uses json4lua (sdl_atf/modules/json4lua)
It would be good if we'll remove it somehow with python.

**Comment by malirod** [comment]
@AGaliuzov, by the way, there are some tests : `sdl_atf/modules/json4lua/examples/tests.lua`
It would be good to reuse these tests.

**Comment by AGaliuzov** [comment]
@malirod Ok , i grasp an idea

**Comment by malirod** [comment]
Not relevant, since lua has separate native lib for json parsing. no need to do this in python.
